import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 文档首页 + 快速上手
  gettingStarted: [
    'index',
    {type: 'autogenerated', dirName: '01-getting-started'},
  ],

  // 功能指南（11 个子板块）
  userGuide: [
    {type: 'autogenerated', dirName: '02-user-guide'},
  ],

  // 应用场景（3 个子板块）
  useCases: [
    {type: 'autogenerated', dirName: '03-use-cases'},
  ],

  // 更多（每个板块独立 sidebar）
  concepts: [
    {type: 'autogenerated', dirName: '04-concepts'},
  ],
  more: [
    {type: 'autogenerated', dirName: '05-more'},
  ],
  faq: [
    {type: 'autogenerated', dirName: '06-faq'},
  ],
};

export default sidebars;
